news-catalyst/google-app-scripts

- Code.js
- Page.html
This PR adds a trigger to rebuild the site to the add-on:
* new deploy hook setup in vercel ([see git integration settings](https://vercel.com/news-catalyst/next-tinynewsdemo/settings/git-integration))
* new script property to store the vercel deploy hook url (click 'show config' to see or set it)
* when publishing, after updating content and 'publishing' in webiny, POST to deploy hook url to trigger rebuild
For now I'm also displaying the JSON response from Vercel's deploy hook in the sidebar for debugging purposes. We'll want to do a sweep of all the text and messaging in the sidebar before this launches.
> Trigger rebuild on publish

- Code.js
Kinda related to issue #82 
I spent the morning benchmarking and trying to streamline the process that gets kicked off when the "Publish" button gets pushed from the sidebar.
Initially, the entire publish process was taking 15 seconds - and that's without any images. To be honest, the image upload doesn't appear to greatly affect the total runtime by more than a second or so. I was surprised by this. I'll do some benchmarking - and if necessary, streamlining - on documents with a lot (more than 5, say) of images in the near future.
Anyway, I was curious about what was taking so long. It appears to be the webiny round trips. 
First, I removed the following webiny requests that seem extraneous:
* publish tags: this was being called every time on every tag on publish; instead, it's now …
> Streamline publishing

- Code.js
Issue #95 
Two changes in this PR:
1. the first image encountered in the doc is now treated as the main image, which means it gets a type of `mainImage` instead of `image`
2. the separate processing for the document `header` is now gone - we were only using it for the main image.
This is testable using the add-on at version 37.
> First image in the doc is the main image, removed header processing

- Code.js
- ManualPage.html
- Page.html
👋  I'd love some feedback on this feature. I consider this version 0.0.0(.0?) but it's functional (hopefully!). This is admittedly a bit rough but I'd rather get your take on how it's working so far instead of waiting on feedback 🙌  Thanks!
This PR lets you take any Google Document and link it to an existing article in Webiny.
To test:
* Open a google doc not currently associated with a webiny article; or use [my test example](https://docs.google.com/document/d/1HjpiubyneR7pGQeW_BFQqpOwKADiFG7ra0NtF51ZS_c/edit?usp=sharing), which is associated (either way works)
* Test using the add-on at "latest code" or version 40: "Manually link doc->article v0"
* Note 2 submenu items for the add-on: Publishing Tools (sidebar we've been using) and Administrator Tools (new)
* Open Administrator tools
* …
> Link a document to an existing article

- Code.js
- ManualPage.html
- Page.html
This fixes the `find on undefined` call as mentioned in issue #132. It should be testable using the add-on at `latest code` by opening a new document -> admin tools -> search -> link.
> Bugfix for associate article

- Code.js
issue #131 
Instead of blindly returning the article data after doing a `getArticle` query, which assumes the data is present, follow the convention I started using of returning an object with info including the `status` of the query (error or success) and a message intended for display, if relevant.
To test, you just have to open a new or existing document and then open the sidebar; this code is executed when the publishing tools sidebar is opened.
> better handling of success/error in retrieving article by ID

- Code.js
Issue #150 
This PR changes how the various script configuration values are stored - see the issue for a more detailed discussion of why.
The folder structure for each TNC, while always important, has become even more so. It needs to start with the organisation name, as that is then used in labelling each value's key for storing the configuration, like so:
* `oaklyn_AWS_ACCESS_KEY_ID`
* `oaklyn_CONTENT_API`
* etc
Do the following when setting up a new TNC/client:
* open the Admin Tools
* fill in the configuration (all fields) and save
* verify all is well by closing the admin tools & reopening; no errors should appear
* finally finish by opening the publishing tools, there should also be no errors, and the locales dropdown should be populated
Getting setup to test this PR is a bit tricky, …
> Scoped script configuration

- Code.js
Issue #155 
Dates are now set in the API as of this PR https://github.com/news-catalyst/reproducible-tinynews-content-api/pull/60
> Published dates now set in the API, no longer set in requests here

- Code.js
This is all related to https://github.com/news-catalyst/google-app-scripts/issues/153
I've admitted mixed a couple things in this PR. I figured while I was making changes to the add-on I'd try to accomplish a few things. Perhaps the attempted coup going on at home has me distracted today :-/ 👎 
1. createArticle no longer modifies the `published` flag
2. updating an article now calls `createArticleFrom` instead of `updateArticle` mutation in the API
3. createArticleFrom also does not modify the `published` flag
4. previous (though recently unused) function updated: publishArticle calls the new `publishArticle` mutation
5. added a similar function for `unpublishArticle`
6. publish & unpublish need to be wired up in the add-on UI, but I don't trust my admittedly limited UX skills with that …
> Create and update article changes; implementation for publishing & unpublishing articles

- ManualPage.html
Closes #165 
It's an improvement from the jumbled mess I had there before...
> cleaned up the layout of admin tools sidebar

- Page.html
> bugfix: don't set form fields to undefined values

- Code.js
- Page.html
Closes #186 and #187 
Two issues came up related to tags that I noticed when I was including a new tag in the list - on preview or publish. This PR fixes both by checking the response from webiny on createTag and by clearing the existing set of tags in the UI before rebuilding the multi-select (`select2`).
> Bug fixes for creating tags

- Code.js
- Page.html
> Change description fields to textareas

- Code.js
- Page.html
> Default SEO titles to article title

- Code.js
- ManualPage.html
- Page.html
Closes issue #194 
I managed to significantly speed up publishing in the sidebar, which was IMO unacceptably slow. I did some benchmarking and instead of finding the issue to be with webiny API calls, it was... with image uploads. Hindsight is 20/20, of course that would take long.
Every single publish (or preview) was uploading every image every time. 
This was happening in a function called `formatElements` which is responsible for taking the body of the Google Doc and returning markup in JSON suitable for storing in Webiny. A typical run time for this function:  **29194 ms**
I realised that I could keep a list of images and their URLs on S3 in the document properties (local google docs storage) as the images are given a persistent ID in the doc. Each run of `formatElements` then checks …
> Feature: performance wins!

- Code.js
- ManualPage.html
- Page.html
Closes #198 
This updates the Admin Tools article search for hasura: articles are searched in the current locale using an ilike query on the headline for the given term.
The actual work associating the document with an article will be done in a later PR.
> Admin tools search articles in Hasura

- Code.js
- Page.html
Closes #200 for preview.
This was a little complicated and while I've tested it, I won't exactly be surprised if issues come up. That said, I did test it numerous times on a new document and then on two different documents repeatedly 🤞 
This PR (latest code in script editor) should:
* create a new article, article translation, article authors (rel), article tags (rel)
* or update an existing article, creating a new article translation, updating any author or tag relations
To test, 
* either open a document that I was using already (both are in the "test as add-on" list)
* or add a new test case using a document in the Tiny News Collective (shared google drive) > Testing > oaklyn > articles folder (there are 2 docs there that I haven't tried: kensington's last-minute gift guide and while …
> Handle preview

- Code.js
- Page.html
closes #204 
This PR implements "unpublish" for the sidebar in hasura. It sets "published: false" on all article_translations in the given locale. It also handles the toggle for the "re-publish", "publish" and "unpublish" buttons in the sidebar.
> hasura-backed unpublish article

- Page.html
This adds form validation to the article form:
* headline, search title and search description are required
* category is required in the db, but there's no way to currently submit this form w/o a category; @TylerFisher do you think I should add "Please select" option or something?
* either one or more authors OR a custom byline is required
Closes #220
> Validation for required fields

- Code.js
- ManualPage.html
This should have been in my last PR, but I hadn't done a `git push` (oops).
> Bugfix for linking doc to article - use locale code not id

- Code.js
- Page.html
Closes #242 
Closes #243 
Use the test case for version 67 as I'll be cleaning up the code (latest code, in other words) today.
> Fixes errors with unpublishing an article

- Page.html
Small update to #269 resulting in that option being called "Other"; latest code in script editor.
> Swapped 'prefer not to say' option for 'other'

- Code.js
Added Spotify/Apple embed detection for podcasts
> Add more embed types

- Code.js
This PR fixes the parsing of list items to properly detect links. Closes https://github.com/news-catalyst/google-app-scripts/issues/291
Tested in https://script.google.com/a/newscatalyst.org/d/1ILURq69o3cYUy6k1n1X6HwxdMfl9xWNhILYuZxgLfeblb3IR15WCMZSj/edit using Latest Code on `Week 0: Startups Playbook` doc (https://docs.google.com/document/d/1AUAKsxGf3kgZZSaWlCExWHMVpFpE5XvUtCal15W_BDc/edit?addon_dry_run=AAnXSK_kxTHf1bA1zPyVu6Tr9vb4d6qUAoYRhcO7EDBKvygjMdAVzs85Mxq7FPuh5PhpsnO_4K2ElJCEWreIfGgTYtt7Eokc7jlgMsMLCKgUckjuaRfufozEv0BeyqvgjljRj1lAlszD)
> bugfix: parse list item links correctly

- Page.html
> Added a '17 or younger' option to the source tracking age dropdown

- Code.js
- GraphQL.js
- ManualPage.html
- Page.html
I merged this too early. I'm seeing a couple issues:
- Still can't republish articles that have already been published
- Can't translate articles properly anymore. I click the translate button, a new document opens, but when I open the sidebar, the locales dropdown is empty and nothing is filled in.
> Revert "Bugfix/prevent overwriting articles same slug"

- GraphQL.js
- Page.html
Closes #348 
Test using version 102 in editor. Sidebar should display the article's previously-selected tags.
> bugfix: request existing tags on article when retrieving

- Page.html
Closes #366 
This is the latest code in the script editor.
> help text and general usability updates

- Code.js
- GraphQL.js
- Page.html
Closes #365 
This change is the latest code in the script editor.
[Related PR in the Hasura repo](https://github.com/news-catalyst/hasura/pull/98)
> Custom canonical url

- Page.html
Closes #375 
* adds a "Please select:" option
* ensures validation displays error message if no value chosen
this is also in the latest code in the script editor (both open PRs are there).
> Dont select first category listed by default

- Notes.md
The new Notes.md describes the major areas of functionality in the sidebar and ambitions for the new way forward backed by a series of API endpoints that encapsulate most of the data-related work for each.
> Features documentation and changes for new API endpoints

- Page.html
this was causing Ang Diaryo's sidebar not to load content correctly
> removed unused condition - use translatedTag

- Code.js
- ManualPage.html
- Page.html
Closes #413 
The admin tools now only includes the settings required for the publishing sidebar to function.
> Update "admin tools" config form
