Code.js
=> bugfix: check if past revisions exist before setting published dates

Code.js, Page.html
Issue #84 was caused by an "Uncaught exception: Forms with file inputs must be the only parameter." happening when you click the 'publish' button. I had made this change to the method signature of the function being called there when I did preview. I didn't realize that `google.script.run.<function()>` could only take one argument.
I fixed this by making a `handlePublish()` function that works similarly to `handlePreview()`, passing `true` as the publish flag, which tells the script whether to save as a draft only (`false`) or to save the draft and publish (`true`).
In order to test that this fixed the problem in the document linked in issue #84 I had to publish the add-on, which I did at version `28` with the code in this PR branch - I was able to successfully publish with this change.
=> Bugfix for 'publish': google app script only allows 1 argument passed to `run()`

Code.js, Page.html
Issue #85 
This PR adds delete functionality to the sidebar:
* a red "Delete Article" button now shows up at the very bottom of the sidebar
* we could add it to the top as well, but I figured maybe we didn't want to make it overly prominent?
* clicking it shows a confirmation dialog, which surprisingly is allowed in google app scripts
* okaying the confirmation triggers the `deleteArticle` app script function
* the `DeleteBasicArticle` mutation is posted to the API
* the doc properties for publishing info (includes dates) and articleID are deleted
* cancelling the confirmation just closes the dialog
You should be able to delete the article, then publish it again (or preview it). I did this many times while testing.
We'll want to provide better explanations around this feature, like …
=> Added a 'delete article' button with confirmation; cleaned up styles

Code.js, Page.html
Issue #89 
This PR adds a field to the sidebar for `Authors`:
* Basic Article content model updated to include "list of references" type "Authors" field to allow one or more authors
* Sidebar requests list of authors from webiny
* Similar to tags, typeahead/select multiple field used for authors
* Unlike tags, you cannot create a new author from here
* Preview and publishing both save the updated article with selected referenced authors
Note: I've left the byline field in for now, though I realise this is confusing. I'm thinking we might want to allow for a freeform byline field in case selecting authors from a predefined list won't work (ex: "by Anonymous" or "by the Editorial Board"). We'd definitely need clearer labelling though. Thoughts?
To test:
1. Open the add-on in [the script …
=> Use referenced authors

Code.js, Page.html
Issue #91 
This will allow us to generate author pages by searching for articles by an author.
Example:
If "The Top 3 British Novels" was written by me and Tyler, the `authors` field would reference both of our author records, and the byline field (which should prolly be renamed) will have `tyler-fisher jacqui-lough` as the text value.
This lets us do a search with the `where input` of:
```
{
"where": {
"byline_contains":"jacqui-lough"
}
}
```
To return all articles that I've written.
It's a bit of a hack, but it works, and it lets us do this kind of search without adding a full indexed search layer. 
I think I should rename this field to something more intention revealing, like `author_slugs` and prevent its value from displaying in the sidebar. I left it in there while adding this …
=> Store author slugs in byline

Code.js, Page.html, appsscript.json
This PR adds some additional functionality to the sidebar to handle publishing docs that aren't articles. The code has been tested (using "latest code" in "run > test as add-on") on both articles and an about page.
* the add-on now has a "document type" concept
* if the document is in a folder called "pages" it is a page
* otherwise it is an article
* my test "About" page has been shared with you and is found here: https://drive.google.com/drive/folders/1-rbjIVjg_Eqf7azKGM5Hu53qneHzGHZy?usp=sharing
* article-specific fields like authors, category, byline, and tags are hidden on page-type docs
* saving a page for the first time calls the `createPage` mutation instead of `createBasicArticle`
* subsequent saves call `createPageFrom` instead of `createArticleFrom`
* previewing a page now …
=> Handle the 'about' page and other regular/non-article pages

Code.js
Issue #98 
This sets the first & last published dates when creating a new article. Subsequent updates already do this.
To test:
* create a new document in Google Docs
* open [the script editor for the add-on](https://script.google.com/a/newscatalyst.org/d/1ILURq69o3cYUy6k1n1X6HwxdMfl9xWNhILYuZxgLfeblb3IR15WCMZSj/edit)
* run > test as add-on > select your new doc
* publish the article
* verify the published dates are set (I did this in the [graphql admin playground](https://d3a91xrcpp69ev.cloudfront.net/cms/manage/production) with query below)
```
query listBasicArticles($where: BasicArticleListWhereInput) {
content: listBasicArticles(where: $where) {
error {
code
message
}
data {
id
headline {
value
}
byline {
value
}
tags {
value {
title {
value
}
slug {
value
}
}
}
authors {
value { …
```
=> Set first and last published dates on initial save for articles

Code.js, Page.html
Issue #103 
This PR includes a lot of changes, but the end result should function the same: the add-on should now work with the scripted version of the API.
Summary:
* there's just one content API now, no more "cms" read & write versions
* and one access token (posted in slack)
* opening the sidebar add-on should load the above as part of its configuration
* preview and publish article should work as expected
=> Updated queries for new api

Code.js, Page.html
Issue: #105 
Category titles used to be accessible in the data under `category.title.value` but are now another level down `category.title.values[0].value`. The category titles should now display.
What's confusing to me is why you see 3 categories but I only see 1... I'm wondering which API your add-on/sidebar is talking to.
While I was fixing this, I also ran into a small issue where Google Docs API gets confused if you ask for the active/current document too many times. We really only need to do this once per function, so I fixed that too.
=> Bugfix: display title found in values for each category in dropdown

Code.js
This change will allow the following query to work. The new `headlineSearch` field stays set to whatever the regular i18n headline is via this PR.
=> Store headline for searching as a regular string

Code.js
This PR has a small bugfix: when setting up the sidebar options (`getArticleMeta()`), request the latest categories from webiny. The sidebar was looking for a cached set instead; I think it's best to always look for the latest instead. We can address performance issues as needed, when needed :)
I noticed this problem when trying to debug https://github.com/news-catalyst/next-tinynewsdemo/issues/162 - I couldn't assign a category because the menu had 1 old category that had been deleted. This should fix that problem!
=> Request latest categories from webiny on load

Code.js
Issue #122 - my recent code changes had an issue trying to load article data without checking if an articleID existed. I had left myself a comment to fix this... and didn't :-/ 
So, this PR wraps all the get-article-data stuff with a check on whether there's an articleID and fixes the sidebar loading on new documents.
=> Bugfix: don't try to load article data without an articleID

Code.js, ManualPage.html, Page.html
Issue #127 
This PR handles the data end of associating google docs with an article in specific locales and will allow us to list edit links in the sidebar for an article in its available translations. These changes store a field as JSON data called `googleDocs` on the article in webiny as mentioned below.
To test this, I verified each scenario by running my list articles query (I'm lazy) in [the graphql playground](https://d27ff8ul81gmi2.cloudfront.net/graphql); I just made sure to include `id`, `googleDocs` and `headline` so I knew which one I was looking at.
=> Store document id info for each locale on articles

Code.js, ManualPage.html, Page.html
This PR has several changes and is a bit lengthy, but the gist is that it takes us closer to supporting multilingual content editing and publishing for the tiny news sites, issues #118, #119 and #120.
The work in this PR takes us through the basics of supporting i18n and multilingual publishing. Details are listed below. I'd like to start up the next round of work in separate PRs (issues #126, #127, #128, #129).
**To test**: open script editor, test as add-on using latest code. Before selecting a locale, the locale picker should display in the Publishing Tools sidebar. After selecting a locale, the chosen locale should be displayed as text in the sidebar. Updating a document works as expected. Associating a new document in another locale preserves the contents of both or all locales.
* we …
=> Locale related changes

ManualPage.html
Issue #133 
Based on the document type (article or page) display only one of the delete buttons.
This is stored as Version 42 in the [script editor](https://script.google.com/a/newscatalyst.org/d/1ILURq69o3cYUy6k1n1X6HwxdMfl9xWNhILYuZxgLfeblb3IR15WCMZSj/edit). I did this to allow testing of PR #139 as "latest code".
To test this PR you'll have to make a new test case for version 42 on a doc; I tested by choosing the "about" document (a `page`) and any other article (I used "available locales" but it shouldn't matter). Then open the Admin Tools. You should see only one delete button.
=> Display either 'Delete Article' or 'Delete Page' button 

Code.js, Page.html, appsscript.json
Issue #129 
This one was a lot more complicated than adding the "edit" links for existing translations of an article because we have to duplicate the google doc and somehow associate this new doc with the same article in webiny... without being able to write to [the Google DocumentProperties Service](https://developers.google.com/apps-script/reference/properties/properties-service#getDocumentProperties()).
I think I've figured out a way, though, that isn't a crazy hack. I'm making this PR as ready for review, but I have a feeling we might have to go a couple rounds with bug fixes - sorry. This was tricky. I'm going to continue testing it as well in whatever scenarios I think of and try to break it.
**To test:**
* Use the test case "Version 45 - 'Article in Default Locale'"
* Opening that …
=> Create links for translations

Code.js, Page.html
Issues #141 and #143 
This PR fixes an issue with how the published flag was set on articles (answer: in a buggy way that wasn't consistent). It also adds a small code update that will regenerate the slug if the article is not published.
To test, use version 48 of the add-on which has this PR branch's code. I used [this document](https://docs.google.com/document/d/1cECfwOjNIX7YSOaDzlOv0JQNFnvDJbD17t6U7dYzdf4/edit?addon_dry_run=AAnXSK9clPOUwR7rbZFa-iekpLdZqE22bhOaqkcOf-f4YNsWFi7n4Xtuea8mC9LdeM0fD8FKGcIm53BaA84lXzcRPh9B05X3auuImyLwuaz-elExpiaXRqBKo68jrPCZA3V4BLwGzlWe_) and made sure to share it with you. 
Try this:
* open [a previously published doc like this one](https://docs.google.com/document/d/1cECfwOjNIX7YSOaDzlOv0JQNFnvDJbD17t6U7dYzdf4/edit?addon_dry_run=AAnXSK9clPOUwR7rbZFa-iekpLdZqE …
=> Updating slug and fixing published status

Code.js, Page.html
Issue #145 
This is very similar to PR #147 and even uses the same front-end function, now renamed for both preview & publish. Instead of doing another roundtrip between the sidebar and backend, the metadata retrieval happens in the `handlePublish` backend function and is returned from there.
=> Speed up publish

Code.js, Page.html
Issue #145 
This PR speeds up the preview process by skipping the extra API roundtrip and having the preview function return the latest `getArticleMeta`data in the same request.
To test: use the latest code and preview an article. No difference in apparent functionality, but should be slightly faster.
=> Speed up preview

Code.js, ManualPage.html
Clicking this button will wipe out data in the google property service - like articleID, isPublished, etc - w/o requiring or expecting access to a Webiny API. So it does everything that 'Delete Article' does except run the 'DeleteArticle' mutation in webiny.
=> Adds a 'clear cache' button to Admin Tools

Code.js
https://github.com/news-catalyst/next-tinynewsdemo/issues/237
After republishing the "Franny Lou’s Porch starts a GoFundMe to buy their building" article with this code (script editor -> test as latest code) the published date appears correctly.
=> Ensure published dates are set on article create and update

Code.js, Page.html
* the check on the presence of `published` was faulty and causing an error to be reported, fixed
* the default status was set to blank, instead of success unless an error occurred, and subsequent checks assumed error by default; this caused issues with both creating and updating an article
* finally I cleaned up some of the extravagant logging that was no longer necessary
=> Bug fixes for a few issues creating and updating articles post-merge

Code.js, Page.html
Closes #158 
This PR updates the buttons in the sidebar to the following:
* Preview: same as before, this button saves the data in the db and returns a link to view
* Publish: saves the doc, sets `published: true`; this button is labelled "Re-publish" if the doc's been published already
* Unpublish: sets `published: false` on the article
Thanks for helping with the UX, @TylerFisher!
=> Updated & simplified sidebar action buttons

Code.js, ManualPage.html, Page.html
Closes #168 
I thought there was a bug in the "Edit in other languages:" feature that creates a new doc in another site-supported locale. While trying to debug this I realized the issue was that the `createArticleFrom` function was passing the wrong variable name for the articleID. 
It should be `revision` now, not `id`. This is something I missed when I changed up the code to do content versioning.
So, the translation/edit in another language feature appeared to be broken, but that was only because it relies on the article data being updated in webiny, and it wasn't being updated.
I also thought, as described in issue #168, that the versioning had broken how localised content was handled. It did, but only by changing the id variable to `revision`, not by changing how the localisation …
=> Bugfix: update article mutation had incorrect variable name

Code.js
Closes #170
small change: grab the locale name from the local document properties and append it as a query string param in the preview url.
related to https://github.com/news-catalyst/next-tinynewsdemo/pull/255
=> bugfix: include locale in the preview url

Code.js, ManualPage.html
Closes #164 
I didn't want to spend a lot of time on this given the rewrite we're likely gonna have to do.
This switches from output of `[object Object]` (helps no one) to `{"message":"Saved configuration.","status":"success"}`
=> small fix: "save config" response

Code.js, ManualPage.html
I noticed an issue setting the locale from the dropdown when I tried to first save an article with the non-default language first (e.g. spanish before saving an english version).
This fixes the small issue causing that.
Along the way, I realized that the deleteArticle code that was picking out document properties to delete was too selective; it wasn't clearing out the locale, or the authors, for instance. So I added a function that makes more sense and deletes all previously stored documentProperties; this is called when you delete the article or clear cache. This helps debugging but also will help if something gets corrupted in the future and you need to start over.
Finally, the update to Google Add-Ons seems to have changed how logging works, despite me choosing to use the legacy …
=> Bugfix setting locale

ManualPage.html
Closes #172 
Before this PR the config data (the aws keys, api url and token, etc) was being loaded when the admin tools sidebar was first opened, then requested again from the API when clicking the "show config form" button; the form would display immediately and then sit there, blank, before getting the API response and data filled in.
This PR:
* eliminates the extra config data API call - not required as we have already loaded it on sidebar open
* fills the data in the config form first
* then displays the config form
I had accidentally started filling in the form when working on this before data showed up a few times, and I was worried about doing this on a real client. Also, this way is just nicer.
Testable using "latest code" from the script editor; open the Admin Tools and click …
=> Fix for config form

Code.js, Page.html
Closes #191 
This was an easy fix - because this list of create & edit translation links is built on every save, I added a line to blank out the section before appending these links.
=> Prevent dupe translation links

Code.js, ManualPage.html, Page.html
Closes #197 
This PR replaces the function "getArticleMeta" and all related code (hopefully - I'll do a bigger sweep of the code when I've gotten all the functionality done) with a version backed by Hasura:
1. opening the "Publishing Tools" sidebar sends a request to look up article data based on the google doc ID and locale
2. this uses the new tables I added this morning that link an article with a google document in Hasura 
3. the following article data is requested: translations of content, slug, tags, authors and category
4. additional data: locales for the org, all categories, all tags, all authors (to populate various select menus)
5. the data is filled into the sidebar form elements where appropriate
Note: this is the first of many PRs for porting the sidebar publishing tools to …
=> Hasura get article

Code.js, Page.html
Noticed this while working on https://github.com/news-catalyst/next-tinynewsdemo/issues/326
the slug value should stored in a hidden field in the form so we're not regenerating it every save. small code change - i had added the hidden field in a prior PR but forgot to set the value :-/
=> Bugfix: pass value of page/article slug from form

Code.js, Page.html
Closes #202 
This sets the `published: true` flag on the new article_translation record that it creates. It also returns the link to the published article similar to the preview functionality.
I think this should work on pages, but that's not tested - I'll work on that next.
=> Publish article for Hasura

Code.js, ManualPage.html, Page.html
Closes #207 
This PR implements the Admin Tools link (part 2 of the article search in that sidebar) feature for Hasura:
1. Create a new google doc
2. Open script editor, Run > Test as add on > add the new document as a test case & save
3. Run the add-on test on the new doc with latest code
4. Open Admin Tools
5. Search for another article: try "philadelphia"
6. Select the "Here's how..." philadelphia article and "en-US" locale: this article is associated with a test doc I've made in en-US, fyi
7. Click link.
What this does:
* Removes the link between the philly article (ID 19) and my test google doc
* Adds your new google doc to the db for en-US
* Links article ID 19 (philly) to your new doc
Once this is done, you should be able to open the publishing tools and see all the philly article …
=> Associate article, Hasura version

Code.js, GraphQL.js, ManualPage.html, Page.html
Closes https://github.com/news-catalyst/next-tinynewsdemo/issues/336
Opening the sidebar now checks if the document corresponds to an article currently featured on homepage. If it is featured, a short message is printed saying so, a link to the homepage editor (configured in the 'Admin Tools') is included, and the "unpublish" button is hidden.
Example of a doc for a featured article: https://docs.google.com/document/d/1cZjl65RWJhBfzngaoV7XgsfoI0GRZfuSOriUzveSCXo/edit?addon_dry_run=AAnXSK_noR3moBAAaYyb4aCJAnRLhVdPPLCry0b-ZZunpnhHPbEGTiXeaLnByCA5BrbgJmykAH6rcr6qzpMrvrl7NMW4up1wx0lEYmPBjp_lHIFv5KAsyHk3tn26nrw4pRTHSNgLr-C-
Otherwise, the "unpublish" button appears as before.
=> check if article is featured on homepage; hide 'unpublish' button if so

Code.js, ManualPage.html
Closes https://github.com/news-catalyst/next-tinynewsdemo/issues/389
This adds a vercel webhook field back to the configuration form (admin tools) and posts to it after any article publish or unpublish by posting to the webhook URL.
=> Republish site on publish/unpublish article

GraphQL.js, Page.html
Closes #263 
We discussed this on slack, but to recap:
* sections are either shown in the nav ("published" in the db) or not
* articles can be assigned to an unpublished/hidden section
* articles will load on the front-end if assigned to a hidden section
In the sidebar, all sections are listed and the ones hidden from the nav say "(hidden)" as of the latest code in this PR - should be testable in the sidebar using run > test > latest code and look like the screenshot below:
with the following sections setup in the tinycms (I'm using oaklyn):
=> label unpublished sections as "(hidden)"

Code.js, GraphQL.js, Page.html
Issue #269
To test this, use version 74 "Source tracking: create or update one source on an article" of the sidebar on an article. The latest code version will be in flux as I need to start coding this feature for multiple sources. Oh, and I was testing using the "Franny Lou's Porch..." article.
This PR:
* adds source tracking fields for a single source to the sidebar for articles
* creates a single source
* updates the source fields
* works in preview and publish
To-do: create & update multiple sources in Hasura, add multiple source fieldsets in the sidebar UI
=> Add or update a single source

Code.js
Closes #265 
I think I've covered all the bases where this add-on gets a name, but I also think it needs time to rollout the changes 🤞
* code (in this PR): menu item changed from "Webiny" to "TinyCMS Publishing Tools"
* note: I haven't been able to find a single place, either "run as add-on" or the published version, where either of those menu item labels are used
* [google cloud platform project](https://console.cloud.google.com/apis/api/appsmarket-component.googleapis.com/googleapps_sdk?project=webiny-sidebar-publishing&authuser=0) associated with the app script renamed to "TinyCMS Publishing Tools"
* marketplace listing info updated, new screenshots and logos included - I suspect that's where it was getting the menu item name I was seeing, and still am: "Tiny News Webiny Publishing …
=> Fixed menu item - removed 'webiny'

Code.js, Page.html
Closes #269 
**UPDATED: this is testable at 'latest code' in the script editor**: responded to feedback on:
* source links not looking like links - you're right, they're now anchor tags
* validation issue: the code was trying to validate the "new source" hidden form(s); I fixed this so any blank source form is not validated & omitted from the list sent to the server
* confirm when trying to publish without any sources: allow to continue (publish anyway) or return to the form for more editing
~This is testable at version 76.~
I think this completes at least the initial version of source tracking for the docs sidebar. This PR adds:
* a list of existing sources to the top of the "Source Tracking" section
* hides all source forms
* adds onclick to each source list item to toggle which source …
=> Clickable list of sources

Code.js, GraphQL.js
Closes #277 
This was simple, just involved renaming each of the queries or mutations twice, once in the actual graphql and again in the function calls fetching or inserting data.
I prefixed all of these with "Addon" to distinguish from similar queries in the front-end. I think that makes sense for monitoring and debugging.
=> Renamed all graphql queries and mutations with descriptive terms

Code.js, GraphQL.js, Page.html
Closes #281 
To test, use the "Testing default headline" test case at latest code; this doc hasn't been previewed or published. The headline and search title fields should default to the document title.
The category/section list should be a mix of "(hidden)" and published section titles; it was appearing as all "(hidden)" because the query wasn't requesting the `published` field value.
=> Bugfix/small UI issues

Code.js, GraphQL.js
https://github.com/news-catalyst/next-tinynewsdemo/issues/682
The main image content remains in the `content` field but is now also stored by itself in a `main_image` field on `article_translations`.
Tested on:
* latest code
* Franny Lou article example
* view the contents of this field in article_translations table id #335
=> Stores the main image content in a new jsonb column

Code.js
related to #291 this small code change prevents list items from being treated as embeddable links, regardless of URL. they are instead stored as regular links.
tested: latest code, on the 'franny lou' doc which I added a silly 3 item list to; one item is a youtube link the other two are to regular non-embed websites. all three render as linked list items in my local front-end. no youtube video is embedded.
=> bugfix prevents list items from being labelled as embed links

Code.js, GraphQL.js
Closes #288 
Before saving the article, clear out the join tables for both article<->authors and article<->tags before saving the article and its related items. (This introduces delete mutations on the joins for both authors and tags, the rest of the logic was being done already.)
Tested on `Local artist Daniel de Jesús releases new album: ‘These songs represent an analysis of my own psyche’` https://docs.google.com/document/d/1M1UZ1BKx1rDdzr7Pu4oH_AU2qS2GirToCQ5uqNBVjVM/edit?addon_dry_run=AAnXSK_ib9KZ-tNjxig-Y-cXxG9j0hMWYADR3Tuen5tJjHZsJMynZNQdyI6Icclt4xaD1HPP_iCvQ-E0ItD4USMBgS50A5f3lks0ppA9ZF_i91rIS0ZKsywYT2lge7uPyO20ELybpwqw using "latest code" in the script editor.
=> Clear article authors and tags before saving

Page.html
Fixes #287 
Rookie error: incorrect parenthetical grouping on the publish/republish form validity check meant invalid forms were passing through to pub/repub. Some noise in this PR as I cleaned up/commented out a bunch of console logs, but the only significant change was the grouping here from:
```
} else if ( formIsValid && (formObject.submitted === "Publish") || (formObject.submitted === "Re-publish") ) {
```
to:
```
} else if ( formIsValid && (formObject.submitted === "Publish" || formObject.submitted === "Re-publish") ) {
```
Test in script editor with latest code; once this is merged, add-on will have to be reversioned & republished.
=> form validation check on publish/republish had incorrect parens

Code.js, GraphQL.js, ManualPage.html
Closes #296 
Adds a "republish all" button to the admin tools sidebar that:
* confirms, then...
* finds all published articles for an org
* opens each article's google doc (behind the scenes) and reprocesses the contents
* reuses the current metadata like search titles
* saves a new published version in hasura
* returns a list of article slugs for all republished articles
=> Republish articles

Code.js
Closes #298 
This includes two fixes: one that validates a slug (and corrects it) and another that properly awaits when processing the current document. The latter is a bug I introduced with the republish-all-articles work, but hey, now fixed!
Testable via latest code in script editor. Turns a slug like " this  has spaces" into "this-has-spaces"
=> Two bugfixes: spaces in slugs and current document processing

Code.js, Page.html
Closes https://github.com/news-catalyst/next-tinynewsdemo/issues/744
Only the first selected tag was being stored because the sidebar html was naively looping over each form data field and assigning it to a new object - this change happened during the addition of source tracking. I think my tests all had the bare minimum of zero or one tag and I missed this issue until you demo'd to the cohort.
This fixes the problem by looping over the `select2` data and pushing each tag onto an array of tags before saving.
Testable with latest code in the script editor. I created a test document which is available in the "Run > Test as add-on" dialog called "All Tags Should Be Published"
To test:
* select more than one tag
* preview or publish
* view the html (preview version or regular pub'd article), …
=> fixes bug where only the first tag is stored

Code.js, GraphQL.js, ManualPage.html
This is the work I alluded to in https://github.com/news-catalyst/next-tinynewsdemo/pull/774
Not sure if we want a delete article button, but it's here in case we do.
As an alternative, here is the graphql to run in Hasura to manually delete an article, including related content (not metrics), by ID:
```
mutation AddonDeleteArticleMutation($article_id: Int) {
delete_published_article_translations(where: {article_id: {_eq: $article_id}}) {
affected_rows
}
delete_article_translations(where: {article_id: {_eq: $article_id}}) {
affected_rows
}
delete_article_slug_versions(where: {article_id: {_eq: $article_id}}) {
affected_rows
}
delete_article_google_documents(where: {article_id: {_eq: $article_id}}) {
affected_rows
}
delete_article_source(where: {article_id: {_eq: $article_id}}) { …
```
=> Admin Tools delete article feature

Code.js, Page.html
Closes #318 
The bug was due to the sidebar not knowing what kind of content this document was: an article or a static page. The line of code that set this value had been moved and was relying on the page to already have an ID, which is why we didn't catch it. 
When I tried to add a new page to the new test org I'm working with, I realized the problem. The fix was very simple - I just had to set the doc type to page or article before checking if it already existed.
Along the way I noticed that the source tracking form was showing up on the static page sidebar, and that the confirmation dialog was happening on publishing static pages. I hid both of these for static pages, and I verified that preview + publish continues to work as expected on articles.
To test, make a new doc in the `pages` …
=> Bugfix: store document type on new or existing articles/pages

Code.js, GraphQL.js, Page.html
Closes #320 
Closes #326 
**Update (Thursday): this  functionality now may be tested with 👉 version 94 👈  in the script editor; includes translations for pages**
**Update (Friday): now displays full locale name, prevents dupe buttons, and opens new translated doc in a new tab in one step**
Based on the locales available for a given organisation and what google documents are associated with an article, this PR updates the publishing tools so, for the Test Diaryo site that publishes in english and filipino:
* a document for an article in english only will display a "Translate to Filipino" button
* upon clicking that "translate" button, a new document will be created and the button updated to "open translation"
* clicking to open will open the new doc in a new browser tab
* subsequent loads …
=> Translate/open translation toggle in publishing tools; done for articles AND pages

ManualPage.html
Closes #320 
** Test with  👉version 93👈 in the script editor **
This removes the following from the Admin Tools sidebar:
* "Debugging info" section - now that the translation tools are in the publishing sidebar, this isn't necessary
* Code related to "click to translate" functionality that is now handled in the publishing sidebar
To test, open a doc from the script editor using 👉**version 93**👈 then open the Admin Tools sidebar. This should render without errors and without the "debugging info" section. I tested an article in the Oaklyn and Test Diaryo orgs and was able to search for an article from the sidebar plus get the confirmation dialog on "delete article".
=> Admin Tools sidebar cleanup

Code.js
Closes #321
** Test using 👉 version 95 👈  in the script editor **
There are a few variations on the link that gets displayed after publishing an article or page:
* with or without a locale
* specially coded pages (About, Donate, Thank You)
* generic static pages (any other 'page' type)
* articles
This PR, available at **version 95** in the script editor, ensures that the 3 special pages _and_ all other generic pages get the right URL for this link. About should be `/en-US/about`, for instance, while a custom History page would be `/en-US/static/history`.
Tested with Oaklyn & Test Diaryo on an article, an About page and a custom static page.
=> Fixes the 'click to view' link

GraphQL.js, Page.html
Closes #327 
Related to the change in the database splitting the author name into first and last, this updates all the graphql queries and the display in the dropdown.
Test with latest code.
=> Handle author first and last names in separate fields, join for display

Code.js, GraphQL.js, Page.html
Closes #330 
Selecting a date in the new date picker will override the first published date, which is otherwise automatically set in the database. This is testable using the latest code in the script editor.
=> Allow backdating stories by overriding first published at date

Code.js, GraphQL.js, Page.html
Closes #336 - fun with time zone conversions in javascript, hasura and postgres
Closes #337 - now initializes the datetime picker in the sidebar for google docs that haven't been previewed or published yet
Test using latest code in the script editor:
* date is once again stored in postgres as timestamptz
* the sidebar code calls this function to format it (without converting time zone): https://stackoverflow.com/a/17415677
* date is then converted by postgres/hasura to UTC
You can also see that the datepicker is now appearing on newly created docs (not yet previewed/published in hasura) by testing with the latest code using the document "Brand New Article Testing Date Picker", which for me appears as the last test case in the editor's list.
=> First published date fixes: time zone, database field type, and new doc date picker

Code.js
Closes #332
Closes #333
These changes are testable using version 99 in the script editor. The front-end formatting of blockquote and hr elements is viewable in [a currently open PR there](https://github.com/news-catalyst/next-tinynewsdemo/pull/845).
* blockquotes: text indented is treated as a new element type of `blockquote`
* hrs: horizontal lines added to the google doc are treated as a new element type of `hr`
=> Handling blockquotes and hrs

Code.js, Page.html
Closes #350 
To test, use latest code on an article, then change the authors and publish. Close & reopen the sidebar, the authors should be correct. You can also verify by checking the published article, but it takes a few moments to update.
This bug was caused by the author field being saved with a single selected author but getting sidestepped for multiple. Oops. It now passes the array no matter what. The plugin that handles tags and authors in the sidebar, `select2`, sends through either a string for one, an array for multiple. This was being managed correctly for tags already.
=> bugfix: save selected authors on every form save (preview/publish)

Code.js, GraphQL.js, Page.html
Closes #367 
_Test using **version 106** in the script editor._
The problem was that I never 🤦‍♀️ coded the unpublish-page feature - it just worked for articles. So if the doc wasn't for an article, the code for "unpublish" was falling through to the "else" scenario, and showing a generic error.
This PR adds an unpublish page mutation + function and the extra use case to the html for the sidebar.
I tested by opening Oaklyn's "Donate" page, unpublishing it, trying to load it on the site, getting a 404, re-publishing it, and reloading the page successfully.
=> Added missing feature to unpublish a page

Code.js, GraphQL.js, Page.html
_Test in the script editor with version 106 - there's a test case for the example doc at this version already._
Using [this example BBG article](https://docs.google.com/document/d/1g4HDw_Ci36MswvW5rRgVxXzXHsctfbAWPwhSv6EkyF8/edit?addon_dry_run=AAnXSK-Fa6zMk1-qXXlNRHhkfQVF0VrFwY_FBRVarXRpyic3f71-eGYsGFInWJoBZKrm7VEEo9AOnNPXpY2vRZtP2Cr1K58Zc4PYr0jryFYkrA_WEKV45T7CdJfHaYvk0PHsJYvKzWm7#heading=h.d8lba76nu1va) I was able to fix two problems related to microsoft word formatting in the doc:
1. the main image now comes through [in the published article](https://next-tinynewsdemo.vercel.app/en-US/articles/community/bbg-community-events)
2. the strange 2 line "HEADING_2" is now parsed as two separate `<h2>` tags
I'm sure there are going to be more Word-related formatting issues, so what I'd like to …
=> Fixes for Word formatting problems on headings and main images

Page.html
Closes #374 
Neither the headline nor the search title will be set to the document name if it's "Untitled document" - this is the latest code in the script editor, and there's a test case for an "Untitled document" already setup.
=> Don't set headline to document title if it's the default untitled value

Code.js
Closes #379 
Test using version `#108` of the code and the "Copy of  BBG Top5Influential Hip Hop Artists" document. I just setup a test case setup for this combination in the script editor for ya.
Fixes include:
* finding all images, which are turned into top-level elements alongside other main element types (blockquote, embed, list, text)
* correct blockquote treatment
* fake "header" text (bold/underlined)
* trailing & leading whitespace in rendered articles (front-end change - https://github.com/news-catalyst/next-tinynewsdemo/pull/983)
=> Bugfixes for more word doc formatting issues

Code.js, Page.html
Closes #381 
Test using version `#109` in the script editor. This adds context to all airbrake errors reported, and if possible (should be in most cases) includes the slug for the organization this error occurred in.
_Note I tested this by deliberately triggering an error in airbrake using the `alertAirbrake('some message');` function call in the `Page.html` file. I removed the call from the file once I verified the error was being reported with context._
Context will vary but can include a lot of helpful details - see screenshots.
=> Report errors to Airbrake with context

Code.js
Closes #386 
Check the test doc using `version 111` (test case already exists) in the script editor to review.
The [article has been published](https://next-tinynewsdemo.vercel.app/en-US/articles/community/test-doc-for-article-features) and images display properly without the hardcoded '.png' extension.
Updated to use [the Google Apps Script-supplied `getContentType()` function on blob data](https://developers.google.com/apps-script/reference/base/blob.html#getcontenttype) to determine the right file extension for each image when uploading to S3.
=> Don't blindly assign all images the '.png' file extension

Code.js
Closes #388 
Test using the case setup for the test document at version 112.
I tried to find a way to calculate the actual image dimensions, but shy of creating a standalone service to do this ([example](https://stackoverflow.com/questions/19257264/how-to-get-the-size-in-pixels-of-a-jpeg-image-i-get-with-urlfetchapp-fetchpho)), I couldn't find a way to derive the height and width. This PR converts the dimensions from `pt` to `px` using the calculation in the linked SO answer.
=> Calculate image height & width by converting pt to px

Page.html
Fixes the reported issue trying to save a new `about` page for Austin Vida but getting an error that a "category/section" is required. It should only be required on articles not static pages.
Test using 'latest code' in the script editor. Happy to publish this ASAP. This branch does not contain the new API code.
=> bugfix: don't require a category unless the doc is for an article

Code.js, ManualPage.html, Page.html
**Update:** I've resolved & merged conflicts with the main branch in this one, deployed this branch as the latest code in the script editor and tested against the now live document API this work integrates with, at least for the `oaklyn` organization. Lookup, preview, publish, and unpublish all worked as expected. I also started [a spreadsheet](https://docs.google.com/spreadsheets/d/1eW7tZPZhBV5h70txOGjuf0gCy7nNGhCFXV57HNKKKj4/edit#gid=0) where examples of each org's API calls are linked.
This PR goes with [the API endpoints PR](https://github.com/news-catalyst/next-tinynewsdemo/pull/1011) in the front-end repo. It is currently the "latest code" in the script editor.
Closes #392
=> Integration with new API

Code.js
We were getting an error on null organization_locales; however, this isn't used anymore and the extra API call to retrieve this data is unnecessary.
=> organization_locales is no longer used, commented out

Page.html
Closes #412 
It's misleading and noisy to alert Airbrake when someone's using the form and forgets to fill in a required field (form validation fails). This PR removes the error reporting on missing required fields.
To test, run > test as add-on > choose any article > latest code > try to preview or publish with any required field missing (example: headline). You should not see an error reported [in the Airbrake Dashboard](https://jacqui-newscatalyst-org.airbrake.io/projects/370377/groups/3264926762952072381?tab=overview).
=> Don't alert airbrake if required form field is missing a value
